site_name: Wiki
nav:
  - Accueil: index.md
  - Jeux:
    - Minecraft:
      - Serveurs:
        - Star Academy: jeux/minecraft/serveurs/star-academy.md
        - NewHorizon:
          - Plugins:
            - Skript Dungeons: jeux/minecraft/serveurs/newhorizon/plugins/skript_dungeons.md
  
  - Services:
    - Docker:
      - Docker: services/docker/docker.md
      - Minecraft: services/docker/minecraft.md
    - Git : services/git.md

theme: 
  name: material
  palette:
    primary: deep purple
    accent: purple
    scheme: slate
